/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nimass;

import javax.swing.JOptionPane;

/**
 *
 * @author MyBook Hype AMD
 */
public class fr_login extends javax.swing.JFrame {

    /**
     * Creates new form fr_login
     */
    public fr_login() {
        initComponents();
        String a = "<HTML><u>Forget Password</u></HTML>";
        btn_forget_pw.setText(a);
        String b = "<HTML><u>Sign Up</u></HTML>";
        btn_signup.setText(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_yellow = new javax.swing.JPanel();
        bg_white = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        bg_blue = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        txt_emailLog = new javax.swing.JTextField();
        txt_passwordLog = new javax.swing.JPasswordField();
        cb_remember_me = new javax.swing.JCheckBox();
        btn_forget_pw = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_signup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg_yellow.setBackground(new java.awt.Color(249, 199, 53));

        bg_white.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Nimas's_logo.png"))); // NOI18N
        logo.setToolTipText("");

        bg_blue.setBackground(new java.awt.Color(38, 124, 191));

        title.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Welcome Back!");

        txt_emailLog.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_emailLog.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_emailLog.setText("       Email");
        txt_emailLog.setToolTipText("");
        txt_emailLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailLogActionPerformed(evt);
            }
        });

        txt_passwordLog.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_passwordLog.setText("adfasfsdfs");
        txt_passwordLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordLogActionPerformed(evt);
            }
        });

        cb_remember_me.setBackground(new java.awt.Color(38, 124, 191));
        cb_remember_me.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_remember_me.setForeground(new java.awt.Color(255, 255, 255));
        cb_remember_me.setText("Remember me");
        cb_remember_me.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_remember_meActionPerformed(evt);
            }
        });

        btn_forget_pw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_forget_pw.setForeground(new java.awt.Color(255, 255, 255));
        btn_forget_pw.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_forget_pw.setText("Forget Password");
        btn_forget_pw.setToolTipText("");

        btn_login.setBackground(new java.awt.Color(238, 53, 57));
        btn_login.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Log In");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("or ");

        btn_signup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_signup.setForeground(new java.awt.Color(255, 255, 255));
        btn_signup.setText("Sign Up");
        btn_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_signupMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg_blueLayout = new javax.swing.GroupLayout(bg_blue);
        bg_blue.setLayout(bg_blueLayout);
        bg_blueLayout.setHorizontalGroup(
            bg_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_blueLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_blueLayout.createSequentialGroup()
                .addGroup(bg_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg_blueLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(bg_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg_blueLayout.createSequentialGroup()
                                .addComponent(cb_remember_me)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_forget_pw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(bg_blueLayout.createSequentialGroup()
                                .addGroup(bg_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_emailLog)
                                    .addComponent(txt_passwordLog, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(bg_blueLayout.createSequentialGroup()
                        .addContainerGap(100, Short.MAX_VALUE)
                        .addGroup(bg_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bg_blueLayout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_signup)))))
                .addGap(88, 88, 88))
        );
        bg_blueLayout.setVerticalGroup(
            bg_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_blueLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(txt_emailLog, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(txt_passwordLog, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(bg_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_remember_me)
                    .addComponent(btn_forget_pw))
                .addGap(56, 56, 56)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(bg_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btn_signup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bg_whiteLayout = new javax.swing.GroupLayout(bg_white);
        bg_white.setLayout(bg_whiteLayout);
        bg_whiteLayout.setHorizontalGroup(
            bg_whiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_whiteLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(49, 49, 49)
                .addComponent(bg_blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bg_whiteLayout.setVerticalGroup(
            bg_whiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_whiteLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(logo)
                .addContainerGap(242, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_whiteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg_blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout bg_yellowLayout = new javax.swing.GroupLayout(bg_yellow);
        bg_yellow.setLayout(bg_yellowLayout);
        bg_yellowLayout.setHorizontalGroup(
            bg_yellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_yellowLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(bg_white, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1750, Short.MAX_VALUE))
        );
        bg_yellowLayout.setVerticalGroup(
            bg_yellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_yellowLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(bg_white, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bg_yellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_yellow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emailLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailLogActionPerformed

    private void txt_passwordLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordLogActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        //validation of inputs
        if (txt_emailLog.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "It is imperative to fill out the email field");
        } else if (txt_passwordLog.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "It is also imperative to fill out the password field");
        } else if (txt_emailLog.getText().equals(fr_signup.email)
                && txt_passwordLog.getText().equals(fr_signup.password)) {
            JOptionPane.showMessageDialog(null, "Login successful, don't forget to be nice ;)");

            this.dispose();
            new fr_transaksi().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Login failed: email and password wrong");
        }

    }//GEN-LAST:event_btn_loginActionPerformed

    private void cb_remember_meActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_remember_meActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_remember_meActionPerformed

    private void btn_signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signupMouseClicked
        this.dispose();
        new fr_signup().setVisible(true);
    }//GEN-LAST:event_btn_signupMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_login.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_login.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_login.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_login.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_blue;
    private javax.swing.JPanel bg_white;
    private javax.swing.JPanel bg_yellow;
    private javax.swing.JLabel btn_forget_pw;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel btn_signup;
    private javax.swing.JCheckBox cb_remember_me;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txt_emailLog;
    private javax.swing.JPasswordField txt_passwordLog;
    // End of variables declaration//GEN-END:variables
}
